config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit]
    resources :lists, only: [:create, :update, :destroy]
    resources :cards, only: [:create, :update, :destroy]

    # resources :items
    # resources :board_memberships
    # resources :card_assignments
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :lists, dependent: :destroy
  has_many :board_memberships, dependent: :destroy
  has_many :members, through: :board_memberships, source: :user

  validates :title, :user, presence: true

  def is_member?(user)
    return true if user.id == self.user_id
    board_memberships.where(user_id: user.id).exists?
  end
end

app/models/board_membership.rb
class BoardMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :list
  has_many :items, dependent: :destroy
  has_many :card_assignments, dependent: :destroy

  default_scope { order(:ord) }
end

app/models/card_asssignment.rb
class CardAsssignment < ActiveRecord::Base
  belongs_to :card
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, :card, presence: true

  belongs_to :card
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, :board, :ord, presence: true

  belongs_to :board
  has_many :cards, dependent: :destroy

  default_scope { order(:ord) }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  has_many :boards
  has_many :card_assignments
  has_many :board_memberships

  validates :email, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, uniqueness: true

  after_initialize :ensure_session_token

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    before_action :require_signed_in!
  end
end

app/controllers/api/boards_controller.rb
module Api
  class BoardsController < ApiController
    def create
      @board = current_user.boards.new(board_params)

      if @board.save
        render json: @board
      else
        render json: @board.errors.full_messages, status: 402
      end
    end

    def destroy
      @board = current_user.boards.find(params[:id])
      @board.destroy

      render json: {}
    end

    def index
      @boards = current_user.boards
      render json: @boards
    end

    def show
      @board = Board.includes(:members, lists: :cards).find(params[:id])

      render :show
    end

    private

    def board_params
      params.require(:board).permit(:title)
    end
  end
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApplicationController
    def create
      @list = List.new(list_params)
      if @list.save
        render json: @list
      else
        render json: @list.errors.full_messages, status: 402
      end
    end

    private

    def list_params
      params.require(:list).permit(:title, :board_id, :ord)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    @current_user ||=  User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    @current_user   = user
    session[:token] = user.reset_token!
  end

  def sign_out!
    current_user.reset_token!
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user])

    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid email/password combination"]
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav id="navtop" class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand navbar-brand-color" style="color:gainsboro" href="#">HelloTrello</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right" id="header-links">
    <% if signed_in? %>
      <!--<li id='add-dropdown' class='dropdown'>
        <button
          class='dropdown-toggle navbar-btn btn btn-default'
          data-toggle='dropdown'><span class='glyphicon glyphicon-plus'></span>
        </button>
      </li>-->
      <!--<li><a id="nav-name" href="javascript:void(0)"><%= current_user.email %></a></li>-->
      <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-default navbar-btn" %></li>
    <% else %>
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloTrello</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <br />
  <br />
  <br />
  
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/root.html.erb
<div class="backdrop">
  <div id="main">
  </div>
</div>
<script type="text/javascript" charset="utf-8">
$(function(){
  HelloTrello.initialize();
});
</script>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Email<br>
    <input name="user[email]" type="text"><br>
  </label><br>
  <label>Password<br>
    <input name="user[password]" type="password"><br>
  </label><br>
  <input type="submit" value="Submit" class="btn btn-primary"><br>
</form>